stages:
  - build
  - push
  - deploy

variables:
  WORKFLOW_STRATEGY: 'gitflow'

include:
  - project: 'infraestructure/gitlab-ci-templates'
    file: '/build/nodejs-build.yml'
    ref: v4.0.6
  - project: 'infraestructure/gitlab-ci-templates'
    file: '/docker/docker-push.yml'
    ref: v4.0.6
  - project: 'infraestructure/gitlab-ci-templates'
    file: '/deploy/trigger-infra.yml'
    ref: v4.0.6

nodejs_build:
  variables:
    NEXT_BUILD_IMAGE: 'node:20-alpine'

trigger_deploy:
  extends: .trigger-infra
  variables:
    APP_NETWORKS: 'nginx-network'
    SECRET_NAME: 'SIGHA-infra'
    APP_VARS: |
      - SISTEMAS_VITE_API_URL
      - SISTEMAS_VITE_SCHOOL
      - VITE_COLOR
